import { Ship, Port, Route, CargoCategoryMaster, VoyageSchedule, PassengerTicket, CargoItem } from '../types';

export const INITIAL_SHIPS: Ship[] = [
  {
    id: 'shp-1',
    code: 'KMP-01',
    name: 'KMP Batumandi',
    type: 'Ferry Ro-Ro',
    passengerCapacity: 850,
    cargoCapacityDWT: 2800,
    maxVehicles: 120,
    deckCount: 4,
    yearBuilt: 2018,
    captainName: 'Capt. Hendra Wijaya, M.Mar',
    callSign: 'YDCB',
    lengthMeters: 110,
    breadthMeters: 18,
    status: 'Aktif Berlayar',
    currentLocation: 'Selat Sunda (Dalam Pelayaran ke Bakauheni)',
  },
  {
    id: 'shp-2',
    code: 'KMP-02',
    name: 'KMP Sebuku',
    type: 'Ferry Ro-Ro',
    passengerCapacity: 920,
    cargoCapacityDWT: 3200,
    maxVehicles: 140,
    deckCount: 4,
    yearBuilt: 2020,
    captainName: 'Capt. Rahmat Fauzi, M.Mar',
    callSign: 'PKBM',
    lengthMeters: 118,
    breadthMeters: 19,
    status: 'Sandar di Pelabuhan',
    currentLocation: 'Dermaga 3 Eksekutif Pelabuhan Merak',
  },
  {
    id: 'shp-3',
    code: 'KMP-03',
    name: 'KMP Portlink III',
    type: 'Ferry Ro-Ro',
    passengerCapacity: 1000,
    cargoCapacityDWT: 3500,
    maxVehicles: 160,
    deckCount: 5,
    yearBuilt: 2019,
    captainName: 'Capt. Bambang Suryono',
    callSign: 'YCP9',
    lengthMeters: 125,
    breadthMeters: 20,
    status: 'Aktif Berlayar',
    currentLocation: 'Perairan Selat Bali Menuju Gilimanuk',
  },
  {
    id: 'shp-4',
    code: 'KM-04',
    name: 'KM Sinabung',
    type: 'Kapal Motor Penumpang',
    passengerCapacity: 1900,
    cargoCapacityDWT: 4500,
    maxVehicles: 45,
    deckCount: 6,
    yearBuilt: 2015,
    captainName: 'Capt. Arif Budiman',
    callSign: 'YDRB',
    lengthMeters: 146,
    breadthMeters: 24,
    status: 'Siaga',
    currentLocation: 'Tanjung Priok Kolam Dermaga Pelni',
  },
  {
    id: 'shp-5',
    code: 'MV-05',
    name: 'MV Samudera Perkasa',
    type: 'Cargo / Kontainer',
    passengerCapacity: 25,
    cargoCapacityDWT: 6200,
    maxVehicles: 0,
    deckCount: 3,
    yearBuilt: 2017,
    captainName: 'Capt. Dedi Kurniawan',
    callSign: 'PKS9',
    lengthMeters: 135,
    breadthMeters: 22,
    status: 'Docking / Perawatan',
    currentLocation: 'Galangan Dok Tanjung Perak Surabaya',
  }
];

export const INITIAL_PORTS: Port[] = [
  {
    id: 'prt-1',
    code: 'MRK',
    name: 'Pelabuhan Merak',
    city: 'Cilegon',
    province: 'Banten',
    dockCount: 7,
    latitude: -5.9328,
    longitude: 105.9983,
    activeDocks: ['Dermaga 1', 'Dermaga 2', 'Dermaga 3 Eksekutif', 'Dermaga 4', 'Dermaga 5'],
  },
  {
    id: 'prt-2',
    code: 'BKH',
    name: 'Pelabuhan Bakauheni',
    city: 'Lampung Selatan',
    province: 'Lampung',
    dockCount: 7,
    latitude: -5.8698,
    longitude: 105.7516,
    activeDocks: ['Dermaga 1', 'Dermaga 2', 'Dermaga 3 Eksekutif', 'Dermaga 4'],
  },
  {
    id: 'prt-3',
    code: 'KTP',
    name: 'Pelabuhan Ketapang',
    city: 'Banyuwangi',
    province: 'Jawa Timur',
    dockCount: 5,
    latitude: -8.1501,
    longitude: 114.4002,
    activeDocks: ['Dermaga Ponton', 'Dermaga MB I', 'Dermaga MB II'],
  },
  {
    id: 'prt-4',
    code: 'GLM',
    name: 'Pelabuhan Gilimanuk',
    city: 'Jembrana',
    province: 'Bali',
    dockCount: 5,
    latitude: -8.1633,
    longitude: 114.4377,
    activeDocks: ['Dermaga Ponton 1', 'Dermaga MB I', 'Dermaga MB II'],
  },
  {
    id: 'prt-5',
    code: 'TPR',
    name: 'Tanjung Priok',
    city: 'Jakarta Utara',
    province: 'DKI Jakarta',
    dockCount: 12,
    latitude: -6.1026,
    longitude: 106.8837,
    activeDocks: ['Dermaga Nusantara', 'Terminal Penumpang 1'],
  }
];

export const INITIAL_ROUTES: Route[] = [
  {
    id: 'rt-1',
    code: 'MRK-BKH',
    name: 'Merak - Bakauheni (Lintas Selat Sunda)',
    originPortId: 'prt-1',
    destinationPortId: 'prt-2',
    distanceNm: 16.5,
    estimatedDurationHours: 2.0,
    baseFarePassenger: 24500,
    baseFareCargoPerTon: 180000,
  },
  {
    id: 'rt-2',
    code: 'BKH-MRK',
    name: 'Bakauheni - Merak (Lintas Selat Sunda)',
    originPortId: 'prt-2',
    destinationPortId: 'prt-1',
    distanceNm: 16.5,
    estimatedDurationHours: 2.0,
    baseFarePassenger: 24500,
    baseFareCargoPerTon: 180000,
  },
  {
    id: 'rt-3',
    code: 'KTP-GLM',
    name: 'Ketapang - Gilimanuk (Lintas Selat Bali)',
    originPortId: 'prt-3',
    destinationPortId: 'prt-4',
    distanceNm: 4.5,
    estimatedDurationHours: 0.8,
    baseFarePassenger: 11500,
    baseFareCargoPerTon: 120000,
  },
  {
    id: 'rt-4',
    code: 'GLM-KTP',
    name: 'Gilimanuk - Ketapang (Lintas Selat Bali)',
    originPortId: 'prt-4',
    destinationPortId: 'prt-3',
    distanceNm: 4.5,
    estimatedDurationHours: 0.8,
    baseFarePassenger: 11500,
    baseFareCargoPerTon: 120000,
  }
];

export const INITIAL_CARGO_CATEGORIES: CargoCategoryMaster[] = [
  {
    id: 'cat-1',
    code: 'GOL-I',
    name: 'Golongan I (Sepeda Dayung)',
    categoryType: 'Kendaraan',
    standardWeightTon: 0.02,
    fare: 28000,
    description: 'Sepeda ontel, sepeda lipat, sepeda kayuh',
  },
  {
    id: 'cat-2',
    code: 'GOL-II',
    name: 'Golongan II (Sepeda Motor <250cc)',
    categoryType: 'Kendaraan',
    standardWeightTon: 0.12,
    fare: 68000,
    description: 'Sepeda motor bebek, matic, sport kapasitas di bawah 250cc',
  },
  {
    id: 'cat-3',
    code: 'GOL-III',
    name: 'Golongan III (Sepeda Motor >250cc)',
    categoryType: 'Kendaraan',
    standardWeightTon: 0.25,
    fare: 145000,
    description: 'Moge, motor roda tiga, motor dengan gandengan',
  },
  {
    id: 'cat-4',
    code: 'GOL-IV',
    name: 'Golongan IV (Mobil Pribadi / Sedan / Minibus)',
    categoryType: 'Kendaraan',
    standardWeightTon: 1.6,
    fare: 495000,
    description: 'Mobil penumpang pribadi panjang sampai dengan 5 meter',
  },
  {
    id: 'cat-5',
    code: 'GOL-V',
    name: 'Golongan V (Bus Sedang / Truk Sedang)',
    categoryType: 'Kendaraan',
    standardWeightTon: 6.5,
    fare: 980000,
    description: 'Kendaraan barang/penumpang panjang 5 - 7 meter',
  },
  {
    id: 'cat-6',
    code: 'GOL-VI',
    name: 'Golongan VI (Bus Besar / Truk Besar)',
    categoryType: 'Kendaraan',
    standardWeightTon: 14.0,
    fare: 1680000,
    description: 'Bus pariwisata besar / Truk Fuso panjang 7 - 10 meter',
  },
  {
    id: 'cat-7',
    code: 'GOL-VII',
    name: 'Golongan VII (Truk Tronton / Trailer)',
    categoryType: 'Kendaraan',
    standardWeightTon: 24.0,
    fare: 2550000,
    description: 'Truk gandeng / tronton trailer panjang 10 - 12 meter',
  },
  {
    id: 'cat-8',
    code: 'CRG-PALLET',
    name: 'Kargo Curah / Pallet',
    categoryType: 'Barang Kargo',
    standardWeightTon: 1.0,
    fare: 350000,
    description: 'Bahan pangan, sembako, palet muatan per ton',
  },
  {
    id: 'cat-9',
    code: 'CRG-CONT20',
    name: 'Kontainer 20ft',
    categoryType: 'Barang Kargo',
    standardWeightTon: 18.0,
    fare: 4500000,
    description: 'Kontainer peti kemas ukuran 20 feet',
  }
];

const now = new Date();
const formatIsoOffset = (hours: number) => {
  const d = new Date(now.getTime() + hours * 3600 * 1000);
  return d.toISOString();
};

export const INITIAL_SCHEDULES: VoyageSchedule[] = [
  {
    id: 'sch-1',
    tripNumber: 'VOY-MRK-081',
    shipId: 'shp-1',
    routeId: 'rt-1',
    dockName: 'Dermaga 3 Eksekutif',
    departureTime: formatIsoOffset(-1.2), // departed 1.2 hrs ago
    estimatedArrivalTime: formatIsoOffset(0.8),
    actualDepartureTime: formatIsoOffset(-1.1),
    status: 'Berlayar',
    weatherCondition: 'Normal / Laut Tenang',
    notes: 'Kondisi pelayaran normal, gelombang 0.8m',
  },
  {
    id: 'sch-2',
    tripNumber: 'VOY-MRK-082',
    shipId: 'shp-2',
    routeId: 'rt-1',
    dockName: 'Dermaga 2',
    departureTime: formatIsoOffset(0.5), // departures in 30 mins
    estimatedArrivalTime: formatIsoOffset(2.5),
    status: 'Boarding',
    weatherCondition: 'Normal / Laut Tenang',
    notes: 'Pemberangkatan tepat waktu, proses muat kendaraan',
  },
  {
    id: 'sch-3',
    tripNumber: 'VOY-KTP-044',
    shipId: 'shp-3',
    routeId: 'rt-3',
    dockName: 'Dermaga MB I',
    departureTime: formatIsoOffset(-0.3),
    estimatedArrivalTime: formatIsoOffset(0.5),
    actualDepartureTime: formatIsoOffset(-0.25),
    status: 'Berlayar',
    weatherCondition: 'Normal / Laut Tenang',
    notes: 'Penyeberangan Selat Bali lancar',
  },
  {
    id: 'sch-4',
    tripNumber: 'VOY-BKH-085',
    shipId: 'shp-1',
    routeId: 'rt-2',
    dockName: 'Dermaga 1',
    departureTime: formatIsoOffset(3.0),
    estimatedArrivalTime: formatIsoOffset(5.0),
    status: 'Terjadwal',
    weatherCondition: 'Normal / Laut Tenang',
    notes: 'Trip balik sore hari',
  },
  {
    id: 'sch-5',
    tripNumber: 'VOY-MRK-089',
    shipId: 'shp-4',
    routeId: 'rt-1',
    dockName: 'Dermaga 5',
    departureTime: formatIsoOffset(6.0),
    estimatedArrivalTime: formatIsoOffset(8.5),
    status: 'Terjadwal',
    weatherCondition: 'Waspada Gelombang 1.5 - 2.5m',
    notes: 'Peringatan BMKG angin kencang di perairan barat',
  }
];

export const INITIAL_PASSENGERS: PassengerTicket[] = [
  {
    id: 'pax-1',
    ticketNumber: 'TIX-2026-00101',
    scheduleId: 'sch-1',
    passengerName: 'Ahmad Syarifudin',
    identityType: 'KTP',
    identityNumber: '3201198504120003',
    gender: 'L',
    age: 39,
    passengerType: 'Dewasa',
    seatClass: 'VIP Eksekutif',
    seatNumber: 'A-12',
    fare: 65000,
    status: 'Boarded',
    bookingDate: formatIsoOffset(-5),
    checkInTime: formatIsoOffset(-1.5),
    qrCodeToken: 'TIX-00101-VERIFIED-QR',
  },
  {
    id: 'pax-2',
    ticketNumber: 'TIX-2026-00102',
    scheduleId: 'sch-1',
    passengerName: 'Siti Rahmawati',
    identityType: 'KTP',
    identityNumber: '3201198808240004',
    gender: 'P',
    age: 36,
    passengerType: 'Dewasa',
    seatClass: 'VIP Eksekutif',
    seatNumber: 'A-14',
    fare: 65000,
    status: 'Boarded',
    bookingDate: formatIsoOffset(-5),
    checkInTime: formatIsoOffset(-1.5),
    qrCodeToken: 'TIX-00102-VERIFIED-QR',
  },
  {
    id: 'pax-3',
    ticketNumber: 'TIX-2026-00103',
    scheduleId: 'sch-1',
    passengerName: 'Muhammad Rizky Syarif',
    identityType: 'Kartu Identitas Anak',
    identityNumber: '3201201509180001',
    gender: 'L',
    age: 9,
    passengerType: 'Anak',
    seatClass: 'VIP Eksekutif',
    seatNumber: 'A-15',
    fare: 35000,
    status: 'Boarded',
    bookingDate: formatIsoOffset(-5),
    checkInTime: formatIsoOffset(-1.5),
    qrCodeToken: 'TIX-00103-VERIFIED-QR',
  },
  {
    id: 'pax-4',
    ticketNumber: 'TIX-2026-00104',
    scheduleId: 'sch-2',
    passengerName: 'Budi Santoso',
    identityType: 'KTP',
    identityNumber: '3171051206800007',
    gender: 'L',
    age: 44,
    passengerType: 'Dewasa',
    seatClass: 'Ekonomi',
    seatNumber: 'DEK-B-42',
    fare: 24500,
    status: 'Checked-in',
    bookingDate: formatIsoOffset(-2),
    checkInTime: formatIsoOffset(-0.2),
    qrCodeToken: 'TIX-00104-VERIFIED-QR',
  },
  {
    id: 'pax-5',
    ticketNumber: 'TIX-2026-00105',
    scheduleId: 'sch-2',
    passengerName: 'Dewi Lestari',
    identityType: 'KTP',
    identityNumber: '3171052207860002',
    gender: 'P',
    age: 38,
    passengerType: 'Dewasa',
    seatClass: 'Bisnis',
    seatNumber: 'B-08',
    fare: 42000,
    status: 'Checked-in',
    bookingDate: formatIsoOffset(-2),
    checkInTime: formatIsoOffset(-0.1),
    qrCodeToken: 'TIX-00105-VERIFIED-QR',
  },
  {
    id: 'pax-6',
    ticketNumber: 'TIX-2026-00106',
    scheduleId: 'sch-2',
    passengerName: 'Haryanto Gunawan',
    identityType: 'SIM',
    identityNumber: '82041234987',
    gender: 'L',
    age: 52,
    passengerType: 'Dewasa',
    seatClass: 'Ekonomi',
    fare: 24500,
    status: 'Terbit',
    bookingDate: formatIsoOffset(-1),
    qrCodeToken: 'TIX-00106-VERIFIED-QR',
  },
  {
    id: 'pax-7',
    ticketNumber: 'TIX-2026-00107',
    scheduleId: 'sch-3',
    passengerName: 'I Made Sudana',
    identityType: 'KTP',
    identityNumber: '5102041903770001',
    gender: 'L',
    age: 47,
    passengerType: 'Dewasa',
    seatClass: 'Ekonomi',
    fare: 11500,
    status: 'Boarded',
    bookingDate: formatIsoOffset(-4),
    checkInTime: formatIsoOffset(-0.4),
    qrCodeToken: 'TIX-00107-VERIFIED-QR',
  },
  {
    id: 'pax-8',
    ticketNumber: 'TIX-2026-00108',
    scheduleId: 'sch-3',
    passengerName: 'Ni Luh Putu Ayu',
    identityType: 'KTP',
    identityNumber: '5102046505800003',
    gender: 'P',
    age: 44,
    passengerType: 'Dewasa',
    seatClass: 'Ekonomi',
    fare: 11500,
    status: 'Boarded',
    bookingDate: formatIsoOffset(-4),
    checkInTime: formatIsoOffset(-0.4),
    qrCodeToken: 'TIX-00108-VERIFIED-QR',
  }
];

export const INITIAL_CARGO: CargoItem[] = [
  {
    id: 'crg-1',
    manifestNumber: 'CRG-2026-00301',
    scheduleId: 'sch-1',
    categoryId: 'cat-4',
    categoryName: 'Golongan IV (Mobil Pribadi / Sedan / Minibus)',
    description: 'Toyota Innova Reborn Hitam Metalik',
    plateNumber: 'B 1492 UZX',
    driverName: 'Ahmad Syarifudin',
    driverPhone: '0812-8877-6655',
    weightTon: 1.75,
    deckPosition: 'Car Deck 1 (Tengah)',
    fare: 495000,
    status: 'Dimuat',
    createdAt: formatIsoOffset(-2.5),
    verifiedAt: formatIsoOffset(-1.6),
  },
  {
    id: 'crg-2',
    manifestNumber: 'CRG-2026-00302',
    scheduleId: 'sch-1',
    categoryId: 'cat-7',
    categoryName: 'Golongan VII (Truk Tronton / Trailer)',
    description: 'Truk Tronton Angkut Semen Sak 400 sak',
    plateNumber: 'BE 9042 BA',
    driverName: 'Supriyadi',
    driverPhone: '0852-6712-3344',
    companyName: 'PT Semen Baturaja Logistik',
    weightTon: 26.5,
    deckPosition: 'Main Deck Belakang (Kanan)',
    fare: 2550000,
    status: 'Dimuat',
    createdAt: formatIsoOffset(-3.0),
    verifiedAt: formatIsoOffset(-1.7),
  },
  {
    id: 'crg-3',
    manifestNumber: 'CRG-2026-00303',
    scheduleId: 'sch-1',
    categoryId: 'cat-6',
    categoryName: 'Golongan VI (Bus Besar / Truk Besar)',
    description: 'Bus Antar Lintas Sumatera (ALS) VIP 34 Seat',
    plateNumber: 'BK 7112 AA',
    driverName: 'M. Nasution',
    driverPhone: '0813-9988-1212',
    companyName: 'PO Antar Lintas Sumatera',
    weightTon: 15.2,
    deckPosition: 'Main Deck Depan (Kiri)',
    fare: 1680000,
    status: 'Dimuat',
    createdAt: formatIsoOffset(-2.8),
    verifiedAt: formatIsoOffset(-1.8),
  },
  {
    id: 'crg-4',
    manifestNumber: 'CRG-2026-00304',
    scheduleId: 'sch-1',
    categoryId: 'cat-2',
    categoryName: 'Golongan II (Sepeda Motor <250cc)',
    description: 'Honda Vario 160 Putih',
    plateNumber: 'A 4581 ZP',
    driverName: 'Rian Pratama',
    driverPhone: '0877-2233-4455',
    weightTon: 0.12,
    deckPosition: 'Car Deck 1 Sisi Lambung',
    fare: 68000,
    status: 'Dimuat',
    createdAt: formatIsoOffset(-2.0),
    verifiedAt: formatIsoOffset(-1.5),
  },
  {
    id: 'crg-5',
    manifestNumber: 'CRG-2026-00305',
    scheduleId: 'sch-2',
    categoryId: 'cat-5',
    categoryName: 'Golongan V (Bus Sedang / Truk Sedang)',
    description: 'Truk Box Ekspedisi JNE Logistics',
    plateNumber: 'B 9801 TEX',
    driverName: 'Wahyu Hidayat',
    driverPhone: '0821-4455-6677',
    companyName: 'PT Tiki Jalur Nugraha Ekakurir',
    weightTon: 7.8,
    deckPosition: 'Main Deck Posisi A',
    fare: 980000,
    status: 'Ditimbang',
    createdAt: formatIsoOffset(-1.2),
    verifiedAt: formatIsoOffset(-0.3),
  },
  {
    id: 'crg-6',
    manifestNumber: 'CRG-2026-00306',
    scheduleId: 'sch-2',
    categoryId: 'cat-4',
    categoryName: 'Golongan IV (Mobil Pribadi / Sedan / Minibus)',
    description: 'Mitsubishi Pajero Sport Dakkar Hitam',
    plateNumber: 'B 2234 RFS',
    driverName: 'Ir. Ferry Gunawan',
    driverPhone: '0811-9876-5432',
    weightTon: 2.1,
    deckPosition: 'Car Deck 1 Menunggu Masuk',
    fare: 495000,
    status: 'Terdaftar',
    createdAt: formatIsoOffset(-0.8),
  },
  {
    id: 'crg-7',
    manifestNumber: 'CRG-2026-00307',
    scheduleId: 'sch-3',
    categoryId: 'cat-7',
    categoryName: 'Golongan VII (Truk Tronton / Trailer)',
    description: 'Truk Pasir Bahan Bangunan Bali',
    plateNumber: 'DK 8831 QA',
    driverName: 'Wayan Sumarta',
    driverPhone: '0878-6543-2109',
    weightTon: 22.0,
    deckPosition: 'Main Deck MB I',
    fare: 2550000,
    status: 'Dimuat',
    createdAt: formatIsoOffset(-1.5),
    verifiedAt: formatIsoOffset(-0.4),
  }
];

export const DEMO_USERS = [
  {
    id: 'usr-admin',
    username: 'admin',
    name: 'Ir. Capt. Suryadi, M.Mar (Administrator Utama)',
    email: 'admin@pelabuhan.go.id',
    role: 'admin' as const,
    password: 'admin123',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=120&auto=format&fit=crop&q=80'
  },
  {
    id: 'usr-operator',
    username: 'operator',
    name: 'Bambang Irawan (Pengatur Dermaga & Jadwal)',
    email: 'operator@pelabuhan.go.id',
    role: 'operator' as const,
    password: 'operator123',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=120&auto=format&fit=crop&q=80'
  },
  {
    id: 'usr-muatan',
    username: 'petugas_muatan',
    name: 'Hadi Prasetyo (Petugas Timbangan & Muatan Kapal)',
    email: 'muatan@pelabuhan.go.id',
    role: 'petugas_muatan' as const,
    password: 'muatan123',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=120&auto=format&fit=crop&q=80'
  },
  {
    id: 'usr-kasir',
    username: 'kasir',
    name: 'Siti Nurhaliza (Petugas Tiketing Penumpang)',
    email: 'kasir@pelabuhan.go.id',
    role: 'kasir' as const,
    password: 'kasir123',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=120&auto=format&fit=crop&q=80'
  }
];
